---
- hosts: web
  become: yes
  become_user: root
  gather_facts: true 
  roles:
     - yum-update
     - nodejs
     - yarn
     - ruby
     - rails
     - application
     - unicorn
     - nginx
     