---
- hosts: web
  become: yes
  become_user: root
  vars:
   public_ip: 35.75.75.64
   application_name: association_tutorial1
  gather_facts: true 
  roles:
     - yum-update
     - nodejs
     - yarn
     - ruby
     - rails
     - nginx