---

- name: gem install rails -v 6.0.3
  shell: bash -lc "gem install rails -v 6.0.3"
  
- name: gem install unicorn -v 6.0.0
  shell: bash -lc "gem install unicorn -v 6.0.0"
  
- name: Install bundler
  gem:
      name: bundler
      user_install: no
      executable: /usr/local/rbenv/shims/gem
      