---

- name: gem install rails -v 6.0.3
  shell: bash -lc "gem install rails -v 6.0.3"
  
- name: application Install 
  git:
      repo: https://github.com/tomoroltuto/rails-for-ansible.git
      dest: /home/ec2-user/rails-for-ansible
  ignore_errors: yes
      
- name: Install bundler
  shell: bash -lc "gem install bundler"

- name: rbenv rehash
  shell: bash -lc "rbenv rehash"
      
- name: bundle install
  shell: bash -lc "bundle install"
  args:
    chdir: /home/ec2-user/rails-for-ansible