---
- name: install wget
  yum: name=wget 
  
- name: setup shell for wget
  shell: wget https://dl.yarnpkg.com/rpm/yarn.repo -O /etc/yum.repos.d/yarn.repo
  
- name: install　yarn
  yum: name=wget
  
# tasks file for myrole