---
- name: Install rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git 
    dest: ~/.rbenv
   
- name: rbenv/bin to PATH
  command: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile

- name: rbenv init
  command: echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
  
- name: read .bash_profile
  lineinfile: >
    dest="~/.bash_profile"
    line='eval "$(rbenv init -)"'
  
- name: Install ruby-build as rbenv plugin
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build