---
- name: install build depends by Ruby
  yum: name={{ item }} state=present
  with_items:
    - git-core
    - gcc
    - gcc-c++
    - gdbm-devel
    - libffi-devel
    - libselinux-python
    - libyaml-devel
    - mysql-devel
    - ncurses-devel
    - openssl-devel
    - sqlite-devel
    - readline-devel
    - zlib-devel
    
 
- name: rbenv install 2.6.3
  command: rbenv install 2.6.3

- name: rbenv global 2.6.3
  command: rbenv global 2.6.3

