---

- name: Install packages
  yum:
    name: '{{ item }}'
    state: latest
    lock_timeout: 180
  with_items:
         - git
         - nss
         - nss-util
         - nspr
         - curl      
         - gcc
         - gcc-c++
         - openssl-devel
         - libyaml-devel
         - readline-devel
         - zlib-devel
         - libffi-devel
         - sqlite-devel
         - libselinux-python
         
- name: Install rbenv
  git:
      repo: https://github.com/sstephenson/rbenv.git
      dest: /home/ec2-user/.rbenv/bin/rbenv
      
- name: rbens set
  template:
      src: rbenv_system.sh.j2
      dest: /etc/profile.d/rbenv.sh
      owner: root
      group: root
      mode: 0755
      
- name: ruby-build  Install 
  git:
      repo: https://github.com/sstephenson/ruby-build.git
      dest: /home/ec2-user/.rbenv/plugins/ruby-build
     
- name: deploy group
  group:
      name: deploy
     
- name: ansible user to deploy group
  user:
      name: ansible
      groups: deploy
     
- name: Change owning group in rbenv directory to deploy
  file:
      path:  /home/ec2-user/.rbenv
      owner: root
      group: deploy
      recurse: yes
      state: directory
     
- name: Install ruby
  shell: bash -lc "rbenv install --skip-existing 2.6.3"
   
- name: global set
  shell: bash -lc "rbenv global 2.6.3"
  
- name: Install bundler
  shell: bash -lc "gem install bundler"

   
- name: rbenv rehash
  shell: bash -lc "rbenv rehash"
